[build]
  publish = "."

# Redirige index.html → /
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# Redirige cualquier .html → URL limpia
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true
